// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/database.types';

// Temporarily hardcode the values to bypass environment variable issues
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://kxcubbibhofdvporfarj.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4Y3ViYmliaG9mZHZwb3JmYXJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MDA4OTcsImV4cCI6MjA1OTk3Njg5N30.tgIV238CB9EeMOWdqM-u8oDhhbCz2f7SzT7ma9jfeEo';

// Debug logging to help troubleshoot environment variable issues
console.log('Environment variables check:', {
  hasUrl: !!SUPABASE_URL,
  hasKey: !!SUPABASE_PUBLISHABLE_KEY,
  urlValue: SUPABASE_URL ? 'present' : 'missing',
  keyValue: SUPABASE_PUBLISHABLE_KEY ? 'present' : 'missing'
});

console.log('Hardcoded fallback values:', {
  url: 'https://kxcubbibhofdvporfarj.supabase.co',
  keyPresent: true
});

if (!SUPABASE_URL) {
  console.error('VITE_SUPABASE_URL is not defined in environment variables');
  throw new Error('Supabase URL is required but not found in environment variables');
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  console.error('VITE_SUPABASE_ANON_KEY is not defined in environment variables');
  throw new Error('Supabase anon key is required but not found in environment variables');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);